name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests using pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Lint the code using flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      # Upload test results as an artifact
      - name: Upload test results to GitHub
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results
